---
title: "eukaryotesV4 database - changes"
author: "Aleix Obiol"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Biostrings)
```

## Functions

### Old

```{r}
# tax_to_fasta <- function(tax, filename, dada = FALSE){
#   if (dada == FALSE){
#     tax_reformat <- 
#       tax %>%
#       mutate(name = paste(OTU, Group, Supergroup, sep = '_'),
#              name = paste0('>',name)) %>% 
#       select(name, seq)
#   } else {
#     tax_reformat <- 
#       tax %>%
#       mutate(name = paste('>Eukaryota',Supergroup, Group, OTU, sep = ';')) %>% 
#       select(name, seq)
#   }
# 
#   do.call(rbind, lapply(seq(nrow(tax_reformat)), function(i) t(tax_reformat[i, ]))) %>% 
#     as_tibble() %>% 
#     write_tsv(filename, col_names = FALSE)
# }
```

### Current

```{r}
tax_to_fasta <- function(tax, filename, dada = FALSE){
  
  if (dada == FALSE){
    
    df <- 
      tax %>%
      mutate(name = paste(OTU, Group, Supergroup, sep = '_'))
    
  } else {
    
    df <- 
      tax %>%
      mutate(name = paste('Eukaryota',Supergroup, Group, OTU, sep = ';')) 
      
  }
  
  fasta <- 
    df %>% 
    select(name, seq) %>% 
    deframe() %>% 
    DNAStringSet()

  writeXStringSet(x = fasta, filepath = filename,width=1e4)
}

summarizer <- function(tax){
  require(knitr)
  tax %>% 
    group_by(Group, Supergroup) %>% 
    summarise("OTU<sub>97</sub> sequences" = n(),
              "Median length (bp)" = round(median(length))) %>% 
    arrange(Supergroup, Group) %>% 
    kable()
} 
```

## Version 2 to 3

```{r}
# version 2 to 3

eukv4_v2 <- read_tsv('db/old_versions/eukaryotesV4_tax_v2.txt')

## tax file

eukv4_v3 <-
  eukv4_v2 %>%
  mutate(Supergroup =
           case_when(
             Group %in% c('Mantamonas','Rigifilida') ~ 'CRuMS',
             Supergroup == 'Eukaryota' ~ 'OtherEukaryota',
             Group %in% c('Apusomonadida','Breviatea') ~ 'OtherEukaryota',
             Supergroup == 'Obazoa' ~ 'Opisthokonta',
             TRUE ~ Supergroup
           ),
         Group = ifelse(Group == 'InSedObazoa', 'InSedOpisthokonta', Group)) %>%
  arrange(Supergroup, Group)

write_tsv(eukv4_v3, 'db/old_versions/eukaryotesV4_tax_v3.txt')

## fasta file

tax_to_fasta(eukv4_v3, 'db/old_versions/eukaryotesV4_v3.fasta')
tax_to_fasta(eukv4_v3, dada = T, 'db/old_versions/eukaryotesV4_v3_dada2.fasta')
```

## version 3 to 4

OTU MPN5387 was classified as MALV-II and it is in fact a Pyramimonadales.

```{r}
eukv4_v3 <- read_tsv('db/old_versions/eukaryotesV4_tax_v3.txt')

## tax file

eukv4_v4 <- 
  eukv4_v3 %>% 
  mutate(Group = ifelse(OTU == 'MPN5387','Pyramimonadales',Group),
         Supergroup = ifelse(Group == 'Pyramimonadales','Archaeplastida',Supergroup))

write_tsv(eukv4_v4, 'db/eukaryotesV4_tax_v4.txt')
tax_to_fasta(eukv4_v4, 'db/eukaryotesV4_v4.fasta')
tax_to_fasta(eukv4_v4, dada = T, 'db/eukaryotesV4_v4_dada2.fasta')

summarizer(eukv4_v4)
```

## version 4 to 5

```{r}
eukv4_v4 <- read_tsv('db/old_versions/eukaryotesV4_tax_v4.txt')

name_changes <- 
  c(Choanomonada = 'Choanoflagellata',
    Colponema = 'Colponemida',
    `X-Cell` = 'Perkinsidae',
    Archamoebae = 'Archamoebea',
    Fractovitelliida = 'Fractovitellida',
    Schizoplasmodiida = 'Schizoplasmodiidae',
    Charophyta = 'Streptophyta',
    Glaucocystophyceae = 'Glaucophyta',
    Nephroselmidophyceae = 'Nephroselmis',
    Rhodophyta = 'Rhodophyceae',
    Goniomonas = 'Cyathomonadacea',
    Katablepharidae = 'Kathablepharidacea',
    Kinetoplastida = 'Kinetoplastea',
    Centrohelida = 'Centroplasthelida',
    Pavlovophyceae = 'Pavlovales',
    Discicristoidea = 'Rotosphaerida',
    Acantharia = 'Acantharea',
    Chlorarachniophyta = 'Chlorarachnea',
    Bolidomonas = 'Bolidophyceae',
    Developayella = 'Developea',
    Diatomea = 'Diatomeae',
    Olisthodiscus = 'Raphidophyceae',
    Picophagea = 'Picophagus',
    Pinguiochrysidales = 'Pinguiophyceae',
    Pirsonia = 'Pirsoniales')

eukv4_v5 <- 
  eukv4_v4 %>% 
  mutate(Group = case_when(Group %in% names(name_changes) ~ name_changes[Group],
                           TRUE ~ Group),
         Supergroup = if_else(Group == 'Picozoa','Archaeplastida',Supergroup))

write_tsv(eukv4_v5, 'db/eukaryotesV4_tax_v5.txt')
tax_to_fasta(eukv4_v5, 'db/eukaryotesV4_v5.fasta')
tax_to_fasta(eukv4_v5, dada = T, 'db/eukaryotesV4_v5_dada2.fasta')

summarizer(eukv4_v5)
```

## version 5 to 6

Change some taxonomic assignations.

```{r}
eukv4_v5 <- read_tsv('db/old_versions/eukaryotesV4_tax_v5.txt')

changes_tax <- 
  tibble::tribble(
             ~OTU,             ~Group,      ~Supergroup,
    "SLVAM901018",      "Nucleomorph", "OtherEukaryota",
    "SLVJF791073",      "Nucleomorph", "OtherEukaryota",
    "SLVJN546121",       "Ascomycota",   "Opisthokonta",
      "SLVL37733",       "Ascomycota",   "Opisthokonta",
    "SLVAB597203",       "BasalFungi",   "Opisthokonta",
    "SLVAB597204",       "BasalFungi",   "Opisthokonta",
        "BMK9285",   "Ancyromonadida", "OtherEukaryota",
    "SLVAY743950",          "Metazoa",   "Opisthokonta",
    "SLVKF211436",          "Metazoa",   "Opisthokonta",
    "SLVKF651077",      "Colponemida",      "Alveolata",
    "SLVDQ267705", "Picocystophyceae", "Archaeplastida",
    "SLVFJ816018",    "Rotosphaerida",   "Opisthokonta",
    "SLVAB085614",     "Schizocladia",  "Stramenopiles"
    )

changes_tax_to_add <- 
  eukv4_v5 %>% 
  filter(OTU %in% changes_tax$OTU) %>% 
  select(-Group, -Supergroup) %>% 
  left_join(changes_tax)

eukv4_v6 <- 
  eukv4_v5 %>% 
  filter(!OTU %in% changes_tax$OTU) %>% 
  bind_rows(changes_tax_to_add) %>% 
  arrange(Supergroup, Group)

write_tsv(eukv4_v6, 'db/eukaryotesV4_tax_v6.txt')
tax_to_fasta(eukv4_v6, 'db/eukaryotesV4_v6.fasta')
tax_to_fasta(eukv4_v6, dada = T, 'db/eukaryotesV4_v6_dada2.fasta')

summarizer(eukv4_v6)
```

## version 6 to 7

```{r}
eukv4_v6 <- read_tsv('db/old_versions/eukaryotesV4_tax_v6.txt')

name_changes <- 
  c(Blastocystis = 'Opalinata',
    Diatomeae = 'Diatomea')

eukv4_v7 <- 
  eukv4_v6 %>% 
  mutate(Group = case_when(Group %in% names(name_changes) ~ name_changes[Group],
                           OTU %in% c("BMK7763", "BMK5345", "BMK5769") ~ 'InSedStramenopiles',
                           OTU %in% c("SLVKF443034", "SLVAJ130893", 
                                        "SLVKF925343", "SLVJN004145") ~ 'Synchromophyceae',
                           OTU %in% c("SLVU73225", "BMK10049", "SLVJN991181", "SLVU73226", "SLVJX946340", "SLVU73219", "SLVU73231", "SLVGU935621", "SLVU73222", "SLVHF549063", "SLVGU935623", "SLVGU935633", "SLVEF165118", "SLVGU935624", "SLVGU935628", "SLVU73221", "SLVGU935622", "SLVJX946336", "SLVGU325513", "SLVHF549067", "SLVHF549064", "SLVGU325515", "SLVGU067831", "SLVAB749074", "SLVJX455151", "SLVAB622324", "SLVHF549070", "SLVKM590553", "SLVAY919713", "SLVAY919803") ~ 'Synurophyceae',
                           OTU %in% c("SLVGAIN01011745", "SLVAJ420694", 
                                      "SLVAJ420692", "SLVHF952607", "SLVAM901023") ~ 'Nucleomorph',
                           OTU == 'MPN3330' ~ 'InSedArchaeplastida',
                           TRUE ~ Group),
         Supergroup = if_else(Group == 'Nucleomorph','OtherEukaryota',Supergroup),
         seq = str_replace_all(seq,'U','T'),
         seq = toupper(seq))   

write_tsv(eukv4_v7, 'db/eukaryotesV4_tax_v7.txt')
tax_to_fasta(tax = eukv4_v7, filename = 'db/eukaryotesV4_v7.fasta')
tax_to_fasta(tax = eukv4_v7, dada = T, filename = 'db/eukaryotesV4_v7_dada2.fasta')

summarizer(eukv4_v7)
```

## version 7 to 8

```{r}
eukv4_v7 <- read_tsv('db/old_versions/eukaryotesV4_tax_v7.txt')

name_changes <- 
  read_tsv('db/old_versions/namechanges_v7_to_v8.txt') %>% 
  deframe()
  
seqs_to_remove <- 
  read_tsv('db/old_versions/remove_v7_to_v8.txt', col_names = 'name')

seqs_to_add <- 
  read_tsv('db/old_versions/addseqs_v7_to_v8.txt') %>% 
  mutate(pident = as.character(pident))

pr2_tax_to_add <- 
  read_tsv('db/old_versions/addpr2_v7_to_v8.txt')

eukv4_v8 <- 
  eukv4_v7 %>% 
  unite(OTU, Group, Supergroup, col = 'name') %>% 
  filter(!name %in% seqs_to_remove$name) %>% 
  mutate(name = case_when(name %in% names(name_changes) ~ name_changes[name],
                          TRUE ~ name),
         name = str_remove(name, '^SLV')) %>% # remove 'SLV' prefix to maintain original accession numbers
  separate(name, sep = '_', into = c('OTU','Group','Supergroup')) %>% 
  bind_rows(seqs_to_add) %>% 
  arrange(Supergroup, Group, OTU) %>% 
  left_join(pr2_tax_to_add) %>% 
  mutate(Supergroup = case_when(Group %in% c('Diplonemea','Euglenida','Heterolobosea','Jakobida','Kinetoplastea') ~ 'Discoba',
                                Group %in% c('Fornicata','Parabasalia','Preaxostyla') ~ 'Metamonada',
                                Group %in% c('Ancyromonadida','Apusomonadida','Breviatea','Malawimonadidae') ~ 'DeepBranching',
                                Group == 'Telonemia' ~ 'Telonemia',
                                TRUE ~ Supergroup))
  
write_tsv(eukv4_v8, 'db/eukaryotesV4_tax_v8.txt')
tax_to_fasta(tax = eukv4_v8, filename = 'db/eukaryotesV4_v8.fasta')
tax_to_fasta(tax = eukv4_v8, dada = T, filename = 'db/eukaryotesV4_v8_dada2.fasta')
```